# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-GnuPG
version:      0.01
version_from: 
installdirs:  site
requires:
    GnuPG:                         0.09
    Template::Plugin::Filter:      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
